/* Official 88-constellation lookup catalog (IAU Latin names + abbreviations). */
const CATALOG_88 = [
  {"name": "Andromeda", "iau": "And", "de": "Andromeda", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Antlia", "iau": "Ant", "de": "Luftpumpe", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Apus", "iau": "Aps", "de": "Paradiesvogel", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Aquarius", "iau": "Aqr", "de": "Wassermann", "kind": "zodiac", "symbol": "♒", "astrologyRange": "20.01.–18.02.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Aquila", "iau": "Aql", "de": "Adler", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Ara", "iau": "Ara", "de": "Altar", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Aries", "iau": "Ari", "de": "Widder", "kind": "zodiac", "symbol": "♈", "astrologyRange": "21.03.–19.04.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Auriga", "iau": "Aur", "de": "Fuhrmann", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Boötes", "iau": "Boo", "de": "Bärenhüter", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Caelum", "iau": "Cae", "de": "Grabstichel", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Camelopardalis", "iau": "Cam", "de": "Giraffe", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Cancer", "iau": "Cnc", "de": "Krebs", "kind": "zodiac", "symbol": "♋", "astrologyRange": "21.06.–22.07.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Canes Venatici", "iau": "CVn", "de": "Jagdhunde", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Canis Major", "iau": "CMa", "de": "Großer Hund", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Canis Minor", "iau": "CMi", "de": "Kleiner Hund", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Capricornus", "iau": "Cap", "de": "Steinbock", "kind": "zodiac", "symbol": "♑", "astrologyRange": "22.12.–19.01.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Carina", "iau": "Car", "de": "Schiffskiel", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Cassiopeia", "iau": "Cas", "de": "Kassiopeia", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Centaurus", "iau": "Cen", "de": "Zentaur", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Cepheus", "iau": "Cep", "de": "Kepheus", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Cetus", "iau": "Cet", "de": "Walfisch", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Chamaeleon", "iau": "Cha", "de": "Chamäleon", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Circinus", "iau": "Cir", "de": "Zirkel", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Columba", "iau": "Col", "de": "Taube", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Coma Berenices", "iau": "Com", "de": "Haar der Berenike", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Corona Australis", "iau": "CrA", "de": "Südliche Krone", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Corona Borealis", "iau": "CrB", "de": "Nördliche Krone", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Corvus", "iau": "Crv", "de": "Rabe", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Crater", "iau": "Crt", "de": "Becher", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Crux", "iau": "Cru", "de": "Kreuz des Südens", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Cygnus", "iau": "Cyg", "de": "Schwan", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Delphinus", "iau": "Del", "de": "Delphin", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Dorado", "iau": "Dor", "de": "Schwertfisch", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Draco", "iau": "Dra", "de": "Drache", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Equuleus", "iau": "Equ", "de": "Füllen", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Eridanus", "iau": "Eri", "de": "Eridanus", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Fornax", "iau": "For", "de": "Ofen", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Gemini", "iau": "Gem", "de": "Zwillinge", "kind": "zodiac", "symbol": "♊", "astrologyRange": "21.05.–20.06.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Grus", "iau": "Gru", "de": "Kranich", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Hercules", "iau": "Her", "de": "Herkules", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Horologium", "iau": "Hor", "de": "Pendeluhr", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Hydra", "iau": "Hya", "de": "Wasserschlange", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Hydrus", "iau": "Hyi", "de": "Kleine Wasserschlange", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Indus", "iau": "Ind", "de": "Indianer", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Lacerta", "iau": "Lac", "de": "Eidechse", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Leo", "iau": "Leo", "de": "Löwe", "kind": "zodiac", "symbol": "♌", "astrologyRange": "23.07.–22.08.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Leo Minor", "iau": "LMi", "de": "Kleiner Löwe", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Lepus", "iau": "Lep", "de": "Hase", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Libra", "iau": "Lib", "de": "Waage", "kind": "zodiac", "symbol": "♎", "astrologyRange": "23.09.–22.10.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Lupus", "iau": "Lup", "de": "Wolf", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Lynx", "iau": "Lyn", "de": "Luchs", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Lyra", "iau": "Lyr", "de": "Leier", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Mensa", "iau": "Men", "de": "Tafelberg", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Microscopium", "iau": "Mic", "de": "Mikroskop", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Monoceros", "iau": "Mon", "de": "Einhorn", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Musca", "iau": "Mus", "de": "Fliege", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Norma", "iau": "Nor", "de": "Winkelmaß", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Octans", "iau": "Oct", "de": "Oktant", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Ophiuchus", "iau": "Oph", "de": "Schlangenträger", "kind": "ecliptic", "symbol": "⛎", "astrologyRange": "", "note": "Die Ekliptik läuft auch durch Ophiuchus; astrologisch gehört er nicht zu den zwölf Tierkreiszeichen."},
  {"name": "Orion", "iau": "Ori", "de": "Orion", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Pavo", "iau": "Pav", "de": "Pfau", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Pegasus", "iau": "Peg", "de": "Pegasus", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Perseus", "iau": "Per", "de": "Perseus", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Phoenix", "iau": "Phe", "de": "Phönix", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Pictor", "iau": "Pic", "de": "Maler", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Pisces", "iau": "Psc", "de": "Fische", "kind": "zodiac", "symbol": "♓", "astrologyRange": "19.02.–20.03.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Piscis Austrinus", "iau": "PsA", "de": "Südlicher Fisch", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Puppis", "iau": "Pup", "de": "Achterdeck", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Pyxis", "iau": "Pyx", "de": "Schiffskompass", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Reticulum", "iau": "Ret", "de": "Netz", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Sagitta", "iau": "Sge", "de": "Pfeil", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Sagittarius", "iau": "Sgr", "de": "Schütze", "kind": "zodiac", "symbol": "♐", "astrologyRange": "22.11.–21.12.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Scorpius", "iau": "Sco", "de": "Skorpion", "kind": "zodiac", "symbol": "♏", "astrologyRange": "23.10.–21.11.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Sculptor", "iau": "Scl", "de": "Bildhauer", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Scutum", "iau": "Sct", "de": "Schild", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Serpens", "iau": "Ser", "de": "Schlange", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Sextans", "iau": "Sex", "de": "Sextant", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Taurus", "iau": "Tau", "de": "Stier", "kind": "zodiac", "symbol": "♉", "astrologyRange": "20.04.–20.05.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Telescopium", "iau": "Tel", "de": "Teleskop", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Triangulum", "iau": "Tri", "de": "Dreieck", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Triangulum Australe", "iau": "TrA", "de": "Südliches Dreieck", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Tucana", "iau": "Tuc", "de": "Tukan", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Ursa Major", "iau": "UMa", "de": "Großer Bär", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Ursa Minor", "iau": "UMi", "de": "Kleiner Bär", "kind": "classical", "symbol": "✦", "astrologyRange": "", "note": "Traditionelles Sternbild der antiken Himmelskarten."},
  {"name": "Vela", "iau": "Vel", "de": "Segel", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Virgo", "iau": "Vir", "de": "Jungfrau", "kind": "zodiac", "symbol": "♍", "astrologyRange": "23.08.–22.09.", "note": "Astrologisches Tierkreiszeichen und astronomisches Sternbild."},
  {"name": "Volans", "iau": "Vol", "de": "Fliegender Fisch", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
  {"name": "Vulpecula", "iau": "Vul", "de": "Füchschen", "kind": "modern", "symbol": "✦", "astrologyRange": "", "note": "Eines der später eingeführten, heute offiziell anerkannten IAU-Sternbilder."},
];
window.CATALOG_88 = CATALOG_88;